### ISSUE TITLE
is it reliable?

### ISSUE THREAD

**Issue by roccomuso** [dotchev/cpu-percentage#2]
why multiply per 10 ? 

https://github.com/dotchev/cpu-percentage/blob/master/index.js#L14

**Comment by dotchev** [comment]
`usage.system` and `usage.user` are in microseconds while `usage.time` is in milliseconds.
We also need to multiply by 100 to get percentage value.
So we have  
(usage.system + usage.user) / (usage.time * 1000) * 100 = (usage.system + usage.user) / (usage.time * 10)
You can also compare the results with your OS tools (e.g. _top_) and you will see they match.
